Repository migalabs/eth-seer, pull requests merged in 2024-12, with the labels that each got.

#179 Expand epoch(s) page
  packages/client/components/layouts/Epochs.tsx
  packages/client/components/layouts/Slots.tsx
  packages/client/pages/epoch/[id].tsx
  packages/client/types/index.ts
  packages/server/controllers/epochs.ts
  packages/server/controllers/slots.ts
Labels: enhancement

#178 Create slashed validators page
  packages/client/components/layouts/SlashedVals.tsx
  packages/client/pages/slashed_validators.tsx
  packages/client/types/index.ts
  packages/server/controllers/slashedValidators.ts
  packages/server/models/server.ts
  packages/server/routes/slashedValidators.ts
Labels: feature

#183 Fix entities endpoint call
  packages/client/components/ui/SearchEngine.tsx
  packages/server/controllers/entitiesList.ts
  packages/server/models/server.ts
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/routes/entitiesList.ts
Labels: enhancement

#181 [fix] text wrap in the entities page
  packages/client/components/ui/EntityCard.tsx
Labels: bug

#184 v2.4.2 Release
  packages/client/components/layouts/Epochs.tsx
  packages/client/components/layouts/SlashedVals.tsx
  packages/client/components/layouts/Slots.tsx
  packages/client/components/ui/Card.tsx
  packages/client/components/ui/EntityCard.tsx
  packages/client/components/ui/SearchEngine.tsx
  packages/client/pages/epoch/[id].tsx
  packages/client/pages/slashed_validators.tsx
  packages/client/pages/transaction/[hash].tsx
  packages/client/pages/validator/[id].tsx
  packages/client/types/index.ts
  packages/server/controllers/entitiesList.ts
  packages/server/controllers/epochs.ts
  packages/server/controllers/slashedValidators.ts
  packages/server/controllers/slots.ts
  packages/server/controllers/validators.ts
  packages/server/models/server.ts
  packages/server/package-lock.json
  packages/server/package.json
  packages/server/routes/entitiesList.ts
  packages/server/routes/slashedValidators.ts
Labels: release
