Repository migalabs/eth-seer, pull requests merged in 2024-01, with the labels that each got.

#159 Fix block page
  packages/client/components/layouts/EpochAnimation.tsx
  packages/client/pages/block/[id].tsx
  packages/server/controllers/blocks.ts
  packages/server/routes/blocks.ts
Labels: bug

#162 Added new clients page
  packages/client/components/ui/Menu.tsx
  packages/client/components/ui/PageDescription.tsx
  packages/client/pages/clients.tsx
  packages/client/public/sitemap.xml
  packages/client/public/static/images/blocks/cubes/languages/go.webp
  packages/client/public/static/images/blocks/cubes/languages/java.webp
  packages/client/public/static/images/blocks/cubes/languages/javascript.webp
  packages/client/public/static/images/blocks/cubes/languages/nim.webp
  packages/client/public/static/images/blocks/cubes/languages/rust.webp
Labels: design

#165 Exclude files from redirection
  packages/client/middleware.ts
Labels: bug

#164 Pagination Improvements
  packages/client/components/ui/Pagination.tsx
  packages/client/components/ui/PaginationIconButton.tsx
  packages/client/pages/blocks.tsx
  packages/client/pages/epochs.tsx
  packages/client/pages/slots.tsx
  packages/client/pages/transactions.tsx
  packages/client/pages/validators.tsx
Labels: feature
